### ISSUE TITLE
data is sent as string and not boolean values

### ISSUE THREAD

**Issue by balexandre** [SparkPost/csharp-sparkpost#10]
As an example for the `Options` property, the serialized version is:

    "{\"content\":{\"template_id\":\"amazon-giftcard\"},\"options\":{\"open_tracking\":\"true\",\"click_tracking\":\"true\",\"transactional\":\"true\",\"sandbox\":\"false\",\"skip_suppression\":\"false\"},\"substitution_data\":{\"code\":\"ABC-123-4567890\",\"amount\":\"$10.00\",\"expiry\":\"12/31/2018\"},\"recipients\":[{\"address\":{\"email\":\"to@domain.com\"}},{\"address\":{\"email\":\"to@domain.com\",\"header_to\":\"bcc@domain.com\"}}]}"

and the boolean values should be `true` instead of `"true"`

This will throw an error saying:

    { 
      "errors": [ 
        { 
          "message": "invalid data format\/type", 
          "description": "field 'options.open_tracking' is of type 'string', but needs to be of type 'boolean'", "code": "1300" 
        } 
        ] 
    }

The issue for the serialization of the `Options` is in the `DataMapper` as it's returned a string and not a boolean value.

I'll add a pull request for this.

**Comment by darrencauthon** [comment]
This was merged with #12, a new branch and PR I created to fix the tests that this change broke.

**Comment by darrencauthon** [comment]
Thank you for your help @balexandre !  Your change has been pushed to nuget as version 1.0.2
