### ISSUE TITLE
Support for CC and BCC

### ISSUE THREAD

**Issue by ganeshvelanki** [SparkPost/csharp-sparkpost#14]
hi, 

I think support for CC and BCC should be made available in the api itself, I tried with my code like below

```
ccList.ForEach(e =>
{
    recipientsList.Add(new SparkPost.Recipient() { Address = new SparkPost.Address() { Email = e, HeaderTo = toAddress } });
 });

transmissionHeaders["CC"] = JsonConvert.SerializeObject(ccList);
```
but I don't see any CC emails could you provide some additional info on this please..

I followed this doc for cc and bcc  
https://support.sparkpost.com/customer/portal/articles/1948014-how-to-add-cc-and-bcc-to-emails

**Comment by darrencauthon** [comment]
I can take a look this evening.  I haven't tried to use CC and BCC yet, but I'll see if I can figure it out.

Perhaps the library could open up some functionality like Mandrill did... Their API allowed the type of the email recipient to be set as "bcc" or "cc"... at least I think it did, it's been a while :confused: .

But just looking at the code you have here, and the quick glance at the spec... do you have the casing right on the transmission header?  I see ```CC``` used in the docs:

![screenshot_032216_091620_am](https://cloud.githubusercontent.com/assets/148768/13954442/bfe45e26-f00e-11e5-95a0-68c7f68839f5.jpg)

**Comment by darrencauthon** [comment]
The care I would want to take with this library is... I think it should mirror SparkPost's API as closely as the language will allow.  We have to be careful not to let it veer off into some other world.

Maybe we ought to at least provide an example in the readme? :smile:

**Comment by ganeshvelanki** [comment]
As far as i looked up the code, this C# api resembles same as sparkpost api, but lots of people are migrating from mandrill to sparkpost, in this time, its better to have at least an example in read me regarding CC and BCC.

and regarding my above code, it has been corrected to "CC". But its behaving like BCC, the email is sent to all parties with out CC/BCC list in it the header( has from and to only.)

Perhaps an example in readme would do actually help.

**Comment by darrencauthon** [comment]
I'll take a look.  I'm sure I'll be needing CC and BCC soon, anyway. :horse_racing:

**Comment by ganeshvelanki** [comment]
Fine, I will update if I found any.

**Comment by JohannesRudolph** [comment]
One way to do it would be to add an extension method on the object iteslf that would take the correct action to add a BCC recipient like ```public static void AddBcc(this Transmission self, Address address)```. 

That way you can add "sugar" on top of the basic API. E.g. I'm currently using this and it apparently works, though I found the Sparkpost docs regarding BCC/CC extremely confusing...

```
    public static class TransmissionExtensions
    {
        public static void AddBccRecipient( this Transmission self, string emailAddress )
        {
            self.Recipients.Add( new Recipient() { Address = new Address() { Email = emailAddress, HeaderTo = "" } } );
        }
    }
```

**Comment by darrencauthon** [comment]
From chris.wilson
```json
{
   "recipients":[
      {
         "address":{
            "email": "to1@example.com.sink.sparkpostmail.com"
         },
      },
      {
         "address":{
            "email": "to2@example.com.sink.sparkpostmail.com"
         },
      },
      {
         "address":{
            "email": "cc1@example.com.sink.sparkpostmail.com"
         },
      },
      {
         "address":{
            "email": "cc2@example.com.sink.sparkpostmail.com"
         },
      },
      {
         "address":{
            "email": "bcc1@example.com.sink.sparkpostmail.com",
         },
      },
      {
         "address":{
            "email": "bcc2@example.com.sink.sparkpostmail.com",
         },
      },
   ],
   "return_path": "chris@YOUR_SENDING_DOMAIN.com",
   "content":{
      "from":"example@YOUR_SENDING_DOMAIN.com",
      "headers":{
         "CC": "<cc1@example.com.sink.sparkpostmail.com>, <cc2@example.com.sink.sparkpostmail.com>"
      },
      "subject": "Sending Email with CC and BCC Recipients",
      "text": "This transmission should cause 6 deliveries, however, bccN will not be revealed"
   }
}
```

**Comment by darrencauthon** [comment]
- [ ] BCC is the built-in behavior, so no need to do anything.
- [ ] If an email recipient is meant to be sent as CC, then it needs to be included as a recipient AND added to the CC header.

**Comment by darrencauthon** [comment]
Given what I've learned, I think it would be ok to update the ```Recipient``` object with an enum of [To/CC/BCC].

**Comment by ganeshvelanki** [comment]
ok, this is cool, enum would be perfectly fine.

**Comment by darrencauthon** [comment]
I have the fix merged into master, and it works fine for me locally.  I'll
get a new version pushed to nuget around lunchtime, and close the ticket
then.

Thanks for bringing this up!

On Monday, March 28, 2016, Ganesh Vellanki <notifications@github.com> wrote:

> ok, this is cool, enum would be perfectly fine.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkPost/csharp-sparkpost/issues/14#issuecomment-202417096>
>


-- 
Darren Cauthon
darren@cauthon.com

**Comment by ganeshvelanki** [comment]
I will also test it with my code and update you if there are any issues.

**Comment by ganeshvelanki** [comment]
I will also test it with my code and update you if there are any issues.

**Comment by ganeshvelanki** [comment]
@darrencauthon 

Hi, I found that cc and bcc feature is not working while sending mails with templates, can you be able to check that once?

**Comment by darrencauthon** [comment]
@ganeshvelanki Can you gist some example of how you are using it?  It "works for me."  :smile:

**Comment by ganeshvelanki** [comment]
Here is my main() of console App

```
        static void Main(string[] args)
        {
            var client = new Client("");
            var transmission = new Transmission();
            transmission.Content.TemplateId = "sampleTemplate";

            var recipient = new Recipient
            {
                Address = new Address { Email = "firstemail@somedomain.com" },
                Type = RecipientType.To
            };

            var recipient2 = new Recipient
            {
                Address = new Address { Email = "ccemail@somedomain.com", HeaderTo = "firstemail@somedomain.com" },
                Type = RecipientType.CC
            };

            transmission.Recipients.Add(recipient);
            transmission.Recipients.Add(recipient2);

            try
            {
                client.Transmissions.Send(transmission).Wait();
            }
            catch (Exception ex)
            {
                throw;
            }
        }
```

**Comment by darrencauthon** [comment]
@ganeshvelanki 

I cannot reproduce this:

![fullscreen_042116_105219_am](https://cloud.githubusercontent.com/assets/148768/14715644/1f502d88-07af-11e6-843a-24d64423cdc4.jpg)

**Comment by ganeshvelanki** [comment]
Yeah, that is acceptable, in fact CC works like above, but have you tried using templateId

`transmission.Content.TemplateId = "sampleTemplate";`

that is not working as expected

**Comment by darrencauthon** [comment]
@ganeshvelanki I just tried it, and I got the emails as expected:

![fullscreen_042116_124118_pm](https://cloud.githubusercontent.com/assets/148768/14718797/58a3f5ce-07be-11e6-8cbd-fea934308eda.jpg)

**Comment by darrencauthon** [comment]
@ganeshvelanki If it helps... this library treats ```To``` and ```BCC``` **exactly the same**.

SparkPost gives us BCC with its default behavior of sending the email to every recipient separately.  The recipient won't know that they were BCC'd on the email, but... given the SparkPost docs as of weeks ago, I couldn't find any way to make that work.  I don't know if it's possible, or... if anybody would want to do it anyway.  

BCC exists as an option only to stop the eventual "How do I send with BCC?" question, and in case the behavior changes in the future.
