### ISSUE TITLE
Add support for SuppressionList API

### ISSUE THREAD

**Issue by JohannesRudolph** [SparkPost/csharp-sparkpost#16]
As the title says, it would be useful to have access to the supression list API through the official sparkpost library.

**Comment by darrencauthon** [comment]
I am working on this support here:  https://github.com/SparkPost/csharp-sparkpost/tree/playing_with_suppression_list

I'll be popping a pull request soon.

**Comment by darrencauthon** [comment]
This support has been added in the latest 1.1.0 release:  https://github.com/SparkPost/csharp-sparkpost/releases/tag/1.1.0

Pop an issue if you have any issues with it!
