### ISSUE TITLE
Cant' send mails, because recipients seems to be empty.

### ISSUE THREAD

**Issue by Robar666** [SparkPost/csharp-sparkpost#17]
I tried to send an example email, code from https://developers.sparkpost.com/

```
var transmission = new Transmission();
transmission.Content.From.Email = "testing@sparkpostbox.com";
transmission.Content.Subject = "Oh hey!";
transmission.Content.Text = "Testing SparkPost - the world\'s most awesomest email service!";
transmission.Content.Html = "<html><body><p>Testing SparkPost - the world\'s most awesomest email service!</p></body></html>";

var recipient = new Recipient
{
    Address = new Address { Email = "developers+csharp@sparkpost.com" }
};
transmission.Recipients.Add(recipient);

var sparky = new Client("<YOUR API KEY>");
sparky.Transmissions.Send(transmission);
```

But I always get the error
```{ "errors": [ { "message": "required field is missing", "description": "recipients or list_id required", "code": "1400" } ] }```
Maybe the recipients won't be serialized correctly?

Domain has been verified.

**Comment by darrencauthon** [comment]
Are you sure that's the code that is being run?  

I just tried copy-pasting that code directly into Linqpad, plugged in a valid API key, and replaced the developers+csharp with my own email address.  And... I got the email.  

![screenshot_032516_070654_am](https://cloud.githubusercontent.com/assets/148768/14043939/284781aa-f258-11e5-95e4-8dd6df5cfe15.jpg)

You can see my email in there.  If you'd like to gist or email me the exact code you are sending (blank out the API key) then I'll see what I can do.

**Comment by Robar666** [comment]
So finally found the culprit.

We are also using Json.Net in our application and we are setting some Json.Net default settings (DefaultValueHandling, TypeNameHandling and Formatting). The "TypeNameHandling" setting breaks  your when serializing the transmission.

You can reproduce the error:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings {
     TypeNameHandling = TypeNameHandling.Auto
};

For now we commenting this setting, but it would be nice if the API also works if the TypeNameHandling is set.

// email sending code
```

**Comment by darrencauthon** [comment]
What I'm going to look into is a way to set this ```TypeNameHandling``` for whatever-it's-using-out-of-the-box within the scope of the serialization used in this library.

I didn't know it was even possible to make this type of global setting! :confused:

Note for later:  

http://www.newtonsoft.com/json/help/html/serializationsettings.htm


Thanks for bringing this up!

**Comment by Robar666** [comment]
Unfortunately we have to set the settings global, because we are using Azure DocumentDb and currently JsonSerializerSettings are not supported.

But there is already a suggestion out there:
https://feedback.azure.com/forums/263030-documentdb/suggestions/6422364-allow-me-to-set-jsonserializersettings 

But thanks for looking into this.

Have a nice day/weekend.

**Comment by darrencauthon** [comment]
Within minutes, version 1.0.5 should be available via Nuget.  

I changed the library to ignore the global settings when making its requests to SparkPost, so your global settings should not cause it to fail.

Thanks for helping to find this potential break for others.  Have a good weekend!
