### ISSUE TITLE
Travis Build

### ISSUE THREAD

**Issue by yepher** [SparkPost/csharp-sparkpost#19]
@richleland 

Just noticed while reviewing the README.md file that the travis build references `ruby-sparkpost.svg` instead of CSharp.

Not sure if this is expected or not so filing an issue so someone can take a look. 

Here is the line in question:
    `[![Travis CI](https://travis-ci.org/SparkPost/ruby-sparkpost.svg?branch=master)]`

**Comment by darrencauthon** [comment]
Should this just be fixed by uploading the svg to this repo, and changing the image link?

**Comment by richleland** [comment]
Pretty sure this is done. 🚁
