### ISSUE TITLE
Support Async API's

### ISSUE THREAD

**Issue by ctolkien** [SparkPost/csharp-sparkpost#26]
Hi, migrating over from Mandrill (as I'm sure are many users).

Would love to see `async` non-blocking api's get added to the surface area.

**Comment by sandrock** [comment]
Hi. I'm not a project member, only a new guy migrating from Mandrill. 

It looks like the [one implemented method](https://github.com/SparkPost/csharp-sparkpost/blob/master/src/SparkPost/Transmissions.cs) is async already. 

Is there something wrong with the current async implementation? Or are you missing the other non-implemented methods?

**Comment by ctolkien** [comment]
Ah, I hadn't actually looked at the code, just at the references from the documentation (which were all `sync`).

**Comment by darrencauthon** [comment]
I wrote that method... and honestly, it was my first time writing any support for ```async```.

The more eyes :eyes:, the better! :smile:

**Comment by darrencauthon** [comment]
@ctolkien I believe this has been handled already -- a link to the code is here:

https://github.com/SparkPost/csharp-sparkpost/blob/eb21934481f9b94f6baf36d45110e6dd75369caf/src/SparkPost/RequestSender.cs#L17

If there's something wrong in this implementation, please let me know.  As I mentioned earlier, this is the first time I've written an OSS library with async support.  My plan is to make all API calls through this library go async.  

I'm going to close this ticket, but please reopen if there is an issue with this implementation.
