### ISSUE TITLE
Nuget Package v1.0.6 is not working

### ISSUE THREAD

**Issue by martinbc** [SparkPost/csharp-sparkpost#27]
Installing the latest package does not install the correct Newtonsoft.Json version.

Nuget Package Install output:

```
PM> Install-Package SparkPost
Attempting to resolve dependency 'Newtonsoft.Json (> 6.0.0)'.
Installing 'Newtonsoft.Json 6.0.1'.
Successfully installed 'Newtonsoft.Json 6.0.1'.
Installing 'SparkPost 1.0.6'.
Successfully installed 'SparkPost 1.0.6'.
Adding 'Newtonsoft.Json 6.0.1' to sparky.
Successfully added 'Newtonsoft.Json 6.0.1' to sparky.
Adding 'SparkPost 1.0.6' to sparky.
Successfully added 'SparkPost 1.0.6' to sparky.
```
Error if you try to send a Transmission:
```
An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, 
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located 
assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 
0x80131040)
```

**Comment by darrencauthon** [comment]
I'll take a look soon, thanks!

**Comment by ganeshvelanki** [comment]
I had this issue previously, but it is resolved after I update NewtonSoft.Json to 8.0, once try to update newtonsoft.Json everywhere in the solution. It could resolve the issue.

**Comment by darrencauthon** [comment]
I don't know the reference got set to 8.0, I must have updated it inadvertently.

**Comment by darrencauthon** [comment]
I just uploaded 1.0.7... I'll be trying @martinbc 's list soon to see if it resolves the issue.

**Comment by darrencauthon** [comment]
@martinbc Just to double-check... are you firing this from an existing .Net project?  Which version of json.net are you using?

**Comment by martinbc** [comment]
It is a command line app built from scratch using VS 2013 Community.

Using the nuget package 1.0.7 the issue was solved.

Thanks!

**Comment by darrencauthon** [comment]
Glad it helped, you are welcome!
