### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by richleland** [SparkPost/csharp-sparkpost#3]
All of our client libraries use TravisCI.

* Set up config file
* Add TravisCI badge

https://docs.travis-ci.com/user/languages/csharp/

**Comment by richleland** [comment]
Config file added to ISSUE-3 branch. @darrencauthon I don't know enough about .NET to understand the errors I see here: https://travis-ci.org/SparkPost/csharp-sparkpost/builds/115531913 - whenever you have a sec if you could take a look that would be great.

**Comment by richleland** [comment]
I think I tracked it down: http://stackoverflow.com/a/32302959/174030 - though I'm not sure if, from your standpoint, this is worth doing. It means changes to settings in the csproj file.

**Comment by darrencauthon** [comment]
We'd have to major changes to the csproj anyway. I think those changes
sound ok.

I won't be able to make the changes until I get back on my laptops later in
the day. If you don't want to wait, why not give it a try? :) don't worry
you can't hurt it. Anything that accidentally breaks can be fixed. Tinker
away...I'd LOVE to have this on Travis!

On Saturday, March 12, 2016, Richard Leland <notifications@github.com>
wrote:

> I think I tracked it down: http://stackoverflow.com/a/32302959/174030 -
> though I'm not sure if, from your standpoint, this is worth doing. It means
> changes to settings in the csproj file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkPost/csharp-sparkpost/issues/3#issuecomment-195753517>
> .
>


-- 
Darren Cauthon
darren@cauthon.com

**Comment by darrencauthon** [comment]
Oh just to warn you: there is one test that is failing,  I have one
integration test that I used during dev, making sure not to check in my
key. It's still in there, but I intended to remove it with more unit tests.

Another option for this failing integration test is to load a testing key
from SparkPost into Travis. Then the tests can fire emails and verify, at
least, that the SparkPost API responded with a success instead of a
failure.

Does Travis run the tests from a certain range of IPs?  If you can load an
environment variable into Travis, let me know and I'll adjust this test.


On Saturday, March 12, 2016, Richard Leland <notifications@github.com>
wrote:

> I think I tracked it down: http://stackoverflow.com/a/32302959/174030 -
> though I'm not sure if, from your standpoint, this is worth doing. It means
> changes to settings in the csproj file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkPost/csharp-sparkpost/issues/3#issuecomment-195753517>
> .
>


-- 
Darren Cauthon
darren@cauthon.com

**Comment by richleland** [comment]
YES: https://travis-ci.org/SparkPost/csharp-sparkpost/builds/115609947

**Comment by darrencauthon** [comment]
It's great that it built, but I don't think it ran the tests. I'll look up
how to run nunit tests with Travis CI

On Saturday, March 12, 2016, Richard Leland <notifications@github.com>
wrote:

> YES: https://travis-ci.org/SparkPost/csharp-sparkpost/builds/115609947
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkPost/csharp-sparkpost/issues/3#issuecomment-195849856>
> .
>


-- 
Darren Cauthon
darren@cauthon.com

**Comment by richleland** [comment]
oh well, um, yeah....

**Comment by richleland** [comment]
![no idea](http://cathyreisenwitz.com/wp-content/uploads/2016/01/no.jpg)

**Comment by darrencauthon** [comment]
Hey it's still a step forward! I've never actually plugged a .Net app into
Travis CI, I'm learning too.

On Saturday, March 12, 2016, Richard Leland <notifications@github.com>
wrote:

> oh well, um, yeah....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkPost/csharp-sparkpost/issues/3#issuecomment-195850693>
> .
>


-- 
Darren Cauthon
darren@cauthon.com

**Comment by richleland** [comment]
btw - this might have the info we need: https://docs.travis-ci.com/user/languages/csharp/

**Comment by darrencauthon** [comment]
It does.  Let me take it from here, I've got this.

**Comment by darrencauthon** [comment]
@richleland It builds and runs the tests. If a test or build fails, it goes red. 

All we need now is the badge. Can you add that?

**Comment by richleland** [comment]
Added - thanks for the work here - awesome to have that set up!
