### ISSUE TITLE
Exception after sending mail

### ISSUE THREAD

**Issue by altozar** [SparkPost/csharp-sparkpost#30]
A few seconds after successfully sending a mail the application crashes with the exception below.  It probably has to do with some sort of callback or asynchronous processing that occurs after the mail has been delivered. I have copied and pasted the sample code in the documentation - ie. not trying to do anything fancy.

![image](https://cloud.githubusercontent.com/assets/11502558/14309871/3c611eae-fbdf-11e5-8227-4bb82c188a60.png)

**Comment by darrencauthon** [comment]
I haven't figured it out yet.  If I had to guess right now, there's something in your request that's causing a null error on the way out.  Still investigating...

**Comment by darrencauthon** [comment]
Can you try this advice here:  https://github.com/SparkPost/csharp-sparkpost#special-note-about-async

Just to double-check that it's not this issue?

**Comment by darrencauthon** [comment]
Closing just because I haven't heard back.  My time is worth... something. :tongue: :watch: :hourglass_flowing_sand:

**Comment by altozar** [comment]
Hi Darren,
of course... We figured out this was due to the reasons explained in the
link I sent you on slack. Thanks for the help

**Comment by waglons** [comment]
We're receiving a very similar error as to what was described above.  The email sends successfully but immediately after a System.NullReferenceException is raised and the w3wp.exe process is terminated.

The code we're using is very similar to the sample code in the documentation and are working with version 1.2.0.

**Comment by darrencauthon** [comment]
@waglons

Would it be possible to get a copy of the entire project or solution?

I ask not because I've asked for code samples from people, but... the code samples always "work for me." 

There's something deeper, but I'm guessing as to what it can be.

Another option is... this library is relatively small.  Could you bring it into your solution raw, run it through a debugger, and tell me exactly where it is throwing?

**Comment by darrencauthon** [comment]
@waglons Here is the code sample of the person that figured it out:

```c#
 Task.Run(async () =>
                    {
                        await client.Transmissions.Send(transmission);
                        transmission.Options.StartTime = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(1));
                        transmission.Content.Subject = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(1)).ToString();
                        await client.Transmissions.Send(transmission);
                        transmission.Options.StartTime = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(2));
                        transmission.Content.Subject = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(2)).ToString();
                        await client.Transmissions.Send(transmission);
                        transmission.Options.StartTime = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(3));
                        transmission.Content.Subject = new DateTimeOffset(deliveryTime).ToOffset(TimeSpan.FromHours(3)).ToString();
                        await client.Transmissions.Send(transmission);
                    }
                  ).Wait();
```

**Comment by darrencauthon** [comment]
^^^ I can't vouch for that code, but it might provide some clue.

**Comment by waglons** [comment]
The code was helpful.  While putting together a solution for you to review I noticed an issue with my asynchronous call and was able to correct it.

Thanks for your help.

**Comment by darrencauthon** [comment]
Glad it helped! 

It might help me... I think I might put in a sync mode, hidden behind the ```Task<T>``` contract.

**Comment by darrencauthon** [comment]
@waglons @altozar Version 1.3.0 has just been released with sync support.

Details here: https://github.com/SparkPost/csharp-sparkpost#special-note-about-async
