### ISSUE TITLE
Transmission "Options" class doesn't have the IP_Pool property

### ISSUE THREAD

**Issue by LeeHester** [SparkPost/csharp-sparkpost#34]
It seems the C# SDK is a bit out of sync with the actual API.  According to [this](https://developers.sparkpost.com/api/#/reference/transmissions), the "Options" for sending a transmission should have an "ip_pool" property.  Maybe I'm missing something here, but I can't find it.  There may be other properties that are missing, this is just the first one that is preventing me from using the SDK.

**Comment by darrencauthon** [comment]
That should be a simple update to make. I'll merge and push it to nuget asap if you pop the PR

**Comment by darrencauthon** [comment]
@LeeHester 

Here's an example of someone adding a missed property, in the same spot even:  https://github.com/SparkPost/csharp-sparkpost/pull/33/files

If you add the string property to the ```Options``` class, it will carry over to the API call.

**Comment by darrencauthon** [comment]
@LeeHester 

Until a dev picks this up, you have another option with the current library.  Create a new options that inherits from ```Options```:

```c#
public class CustomOptions : Options
{
    public string IpPool { get; set; }
}
```

You can set your new options on a transmission:

```c#
var transmission = new Transmission { Options = new CustomOptions() };
transmission.IpPool = "x";
```

That's all you should have to do, the value will carry through as ```ip_pool```.  This library is based on conventions, so it looks at the object provided to determine what to send, and how.

**Comment by LeeHester** [comment]
Darren, thanks for the help.  I've been able to work around it by cloning your SDK and putting a copy of your code right in my project, and adding the property to "Options" in my copy of the code.  It's not ideal, but it will work fine until this gets added.  I've been under the gun to complete my company's integration with SparkPost, so I haven't had time to make a PR for this change, and wouldn't have had time to wait for a new Nuget package anyway.  I should be able to make a PR for this issue this week, unless you guys beat me to it.  Thanks again.

**Comment by darrencauthon** [comment]
@LeeHester You should be able to get this property on nuget in a few minutes:

https://www.nuget.org/packages/SparkPost/1.1.1
