### ISSUE TITLE
SparkPost-API 1.1.0 Sending Transmission Fails

### ISSUE THREAD

**Issue by ManuLin** [SparkPost/csharp-sparkpost#36]
I have updated the SparkPost-API to version 1.1.0 and receive the following exception when sending a transmission:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, 
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located 
assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 
0x80131040)

I'm using Newtonsoft.Json version 8.0.3. Any help appreciated.

**Comment by cpntgt** [comment]
This is not related to SparkPost. I have gotten this error before. Make sure you have the Newtonsoft.Json entry in your Web.config under the website root. What I have is the following:

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>

**Comment by darrencauthon** [comment]
This library also requires .Net 4.5, so I would check on that as well.

**Comment by darrencauthon** [comment]
I'm going to close this for now... but please feel free to respond here and reopen if it is discovered to be an issue with this library.
