### ISSUE TITLE
Allow use of proxy in RequestSender

### ISSUE THREAD

**Issue by sarus** [SparkPost/csharp-sparkpost#38]
Hello,

We're porting some code that we used from Mandrill and so far everything has been a breeze.  One issue we've run into is that we need to be able to set the underlying `HttpClient` in `RequestSender` to use a proxy

```
var httpClientHandler = new System.Net.Http.HttpClientHandler
{
     Proxy = WebRequest.GetSystemWebProxy()                
};
var client = new HttpClient(httpClientHandler);
```

Can you allow a custom HttpClientHandler to be set at the `Client` or `Transmissions` level that can be passed through to the `RequestSender` so we can modify the behavior there in the `RequestSender.Send` method?

**Comment by darrencauthon** [comment]
Hmm.... I think so.  Looking...

**Comment by darrencauthon** [comment]
@sarus Can you check the PR I just created and check that it will work for you?

**Comment by sarus** [comment]
That looks perfect.  Thank you for being so responsive.

**Comment by darrencauthon** [comment]
np @sarus glad to help.  I normally wouldn't jump on this so quickly, but... it was an interesting problem to solve. :smile:

In a few minutes, it should appear on Nuget as 1.1.1

https://www.nuget.org/packages/SparkPost/1.1.1

**Comment by sarus** [comment]
Thanks again!  Already making use of it.
