### ISSUE TITLE
Sub Accounts

### ISSUE THREAD

**Issue by ZA1** [SparkPost/csharp-sparkpost#45]
I need the ability to work with subaccounts. I realize that you can do it now with the custom settings on the client, but it would be nice if it could be integrated.

I am happy to do the changes and submit a PR if this is not already in the works.

**Comment by darrencauthon** [comment]
It's not on my list of things to do, I've just been coding things as I've needed them.  It would be great if you could add this feature!

If you want a template to follow, I just merged in support for webhooks (#35).  I designed this library to follow conventions, which should hopefully make implementing the rest of the SparkPost API easier.  It should just be a matter of matching up their data and requests with C# objects that are named to match.  

If you want a starting point, I'd start with the webhooks object below.  It has the four crud operations defined in their API, and you'll be able to see that each method basically just maps the API url to a little bit of code that handles it.  The ```DataMapper``` class does most of the work... and even then, it uses conventions.  

https://github.com/SparkPost/csharp-sparkpost/pull/35/files#diff-99145ac9df918d5a892ff60bac06934cR6

The only thing that's not conventional (yet) is the mapping of data from their API results back to C# objects.  So sending data to SparkPost can be handled by the ```DataMapper```, but bringing data back requires some code like this:  

https://github.com/SparkPost/csharp-sparkpost/pull/35/files#diff-bcf8ff95c929be57634bee63176b6653R24

**Comment by darrencauthon** [comment]
I appreciate any support, even if it's not the full subaccounts implementation.  Let me know if you have any questions!

**Comment by ZA1** [comment]
I have added a PR for subaccounts: #53

**Comment by darrencauthon** [comment]
This was resolved by #53 and deployed to nuget as version 1.4.0.
