### ISSUE TITLE
Defining SubstitutionData all in capital letters is not working

### ISSUE THREAD

**Issue by babakarj** [SparkPost/csharp-sparkpost#49]
Actually, I'm not sure if this is a bug or a rule in your system, but defining _SubstitutionData_ in capital is not working and sends email with no SubstitutionData data.
`transmission.SubstitutionData.Add("NAME", "a-name");`
And in Template markup:
`<div>{{NAME}}</div>`
Changing both in lower case (_name_) makes things working.

**Comment by darrencauthon** [comment]
@babakarj Thanks for bringing this up.  This has been resolved in 1.3.0.
