### ISSUE TITLE
HTML code in variable

### ISSUE THREAD

**Issue by ManuelFunciona** [SparkPost/csharp-sparkpost#58]
Hi people,

I have a problem when I want replace a value containing html code in a variable of SparkPost.

Example code in C#:
string variable = "Hello<<newline>>World";
...
transmission.SubstitutionData["myVariable"] = variable;

Example code in HTML (email):
       {{ myVariable }}

Result:
 Hello<<newline>>World

But I want this result:

Hello
World

Anyone know a solution?

Thanks!!!!

**Comment by darrencauthon** [comment]
Try
 
```
{{{ myVariable }}}
```

I believe that's the way to show the raw value.

**Comment by rdawemsys** [comment]
That's right, use triple-curlies if you do not want the value to be HTML-escaped. Double-curlies do automatic HTML escaping. There is some more detail about this in https://developers.sparkpost.com/api/#/introduction/substitutions-reference

**Comment by ManuelFunciona** [comment]
Perfect!!!

{{{ myvariable }}} is the solution.

Thanks for the responses

**Comment by darrencauthon** [comment]
No problem.
