### ISSUE TITLE
Feature: Message Events API support

### ISSUE THREAD

**Issue by kirilsi** [SparkPost/csharp-sparkpost#60]
Requirements: 
Reading bounces via Message Events API.
Simple query support (search for message event data by event type and date range).
Results paging support (results per page, page number query parameters).

This feature is already under development.
I will also try to include support for all other event types and all query parameters for Message Events API.
I will create a Pull Request when it is finished and fully tested.

**Comment by darrencauthon** [comment]
That would be great, thank you!!!

**Comment by darrencauthon** [comment]
This should be available with version 1.5.0, thanks again!
