### ISSUE TITLE
.netframework 4.5.1

### ISSUE THREAD

**Issue by yhuangf** [SparkPost/csharp-sparkpost#7]
We are using 4.5.1, and found out that spark-post was rolled back to 4.5 3 days ago. Any particular reason for the rolling back? Any projected time the package will be available to 4.5.1 .net solutions?

The nuget package installation returns errors:
**install-package : Could not install package 'SparkPost 1.0.0.13918'. You are trying to install this package into a project 
that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author**

**Comment by richleland** [comment]
tagging @darrencauthon for insight

**Comment by darrencauthon** [comment]
I can reproduce the problem:

![screenshot_031816_063856_am](https://cloud.githubusercontent.com/assets/148768/13876707/17d738c6-ecd4-11e5-98b2-2787254500ac.jpg)

**Comment by darrencauthon** [comment]
![fullscreen_031816_073827_am](https://cloud.githubusercontent.com/assets/148768/13878009/68a7b82c-ecdc-11e5-9356-0513a854a883.jpg)

**Comment by darrencauthon** [comment]
Hi @yhuangf can you see if the 1.0.1 version works better for you?

I believe it should, it goes back to 4.5. Closing on that assumption, but please reopen if it 1.0.1 on nuget does not work for you.

**Comment by yhuangf** [comment]
Hi Darren,

Really appreciated the updating. Yes now 1.01 works fine with me. Confirmed!

Thanks again!

Cheers

Ethan

**Comment by darrencauthon** [comment]
You are very welcome!
It's still a new library, so please let us know if there are any issues! :)

Get Outlook for iOS




On Fri, Mar 18, 2016 at 9:02 AM -0700, "yhuangf" <notifications@github.com> wrote:










Hi Darren,



Really appreciated the updating. Yes now 1.01 works fine with me. Confirmed!



Thanks again!



Cheers



Ethan





On Fri, Mar 18, 2016 at 8:20 AM, Darren Cauthon <notifications@github.com>

wrote:
