### ISSUE TITLE
nuget 1.6.0

### ISSUE THREAD

**Issue by csprofiles-sowens** [SparkPost/csharp-sparkpost#76]
When I try downloading the 1.6.0 version of sparkpost library via nuget it gets the nupkg file, but it's not actually downloading and referencing the library.  I had no problems with the last version I was coding against (1.4.0).  Am I missing something?

**Comment by darrencauthon** [comment]
Oh, I just tried and noticed a similar problem... I'll have a 1.6.1 up shortly.

**Comment by darrencauthon** [comment]
@csprofiles-sowens This should be resolved with 1.6.2.  You can pull it from Nuget now.

Sorry for the issue! :disappointed:

**Comment by csprofiles-sowens** [comment]
No problems downloading the latest version.  Thanks for all the hard work.

**Comment by darrencauthon** [comment]
@csprofiles-sowens np.  Thanks for reporting, and let us know if anything else comes up.
