### ISSUE TITLE
Could not install package 'SparkPost 1.0.0.13918'. with NETFramework

### ISSUE THREAD

**Issue by richleland** [SparkPost/csharp-sparkpost#8]
From one of our awesome customers:

> im trying to install SparkPost using Nugget Package manager console and the
command: Install-Package SparkPost as the web says. My problem is that
seems that is not compatile with .net framework version 4.5.

>"*Install-Package : Could not install package 'SparkPost 1.0.0.13918'. You
are trying to install this package into a project that targets
'.NETFramework,Version=v4.5', but the package does not contain any
assembly references or content files that are compatible with that
framework. For more information, contact the package author*."

> Do you know if there's any package compatible with .net Framework, 4.5

**Comment by darrencauthon** [comment]
I'm closing. I was able to reproduce and resolve the issue in the related PR. Fixed in 1.0.1
